#!/bin/bash

echo """
#################
Inicia o download
#################"""

wget -v https://us02web.zoom.us/client/latest/zoom_amd64.deb

echo """
#################
Inicia Instalação
#################"""

sudo dpkg -i *.deb && rm *.deb



